[package]
name = "rs-geo-playground"
version = "0.1.0"
authors = ["Magnus Kulke <mkulke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstar = "0.6.0"
osmpbfreader = "0.13.2"
osm_boundaries_utils = "0.5.0"
geojson = { version = "0.16.0", features=["geo-types"] }
geo-types = "0.4.3"
rayon = "1.2.0"
serde_json = "1.0.41"
geo = "0.12.2"
